version: "3.9"

services:
  db:
    image: postgres:15.2
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}
    volumes: 
      - db_data:/var/lib/postgresql/data

  web:
    image: ${WEB_IMAGE:-ghcr.io/lcjtrifork/kanban:latest}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/postgres
      SECRET_KEY_BASE: GoMXqIj1d+6zUUMS6J1ubLgy9ag7r9UvYZkCJSXIBHOMQRcOuXEvWENCXllIEKPM
      PHX_HOST: "localhost"
    ports:
      - 4000:4000
    depends_on:
      - db
    command: >
      bash -c "bin/migrate && bin/server"

volumes:
  db_data: